### ISSUE TITLE
Add multiprocessing support back to Heroku docker R

### ISSUE THREAD

**Issue by doprdele** [hmdc/heroku-docker-r#1]
# Story Description
R is single-threaded. The previous Heroku R buildpack - https://github.com/hmdc/heroku-buildpack-r - now deprecated - used Apache to LB across N R Shiny instances, N being the number of cores divided by two.

Why divide by 2? R memory usage is huge. Heroku dynos have between 4 and 8 cores available, with more available at larger instance types. Running 4 to 8 Shiny processes is not feasible, financially or technically, given that there is no suitable "large memory" instance available in Heroku.

However, most apps can at least support 2 concurrent R Shiny instances. Add this support back to improve performance.

Note there are /better/ ways to increase performance with the use of Promises - https://rstudio.github.io/promises/articles/overview.html - but that requires code changes and a familiarity with the concept of asynchronous/event-driven programming.

# Helpful Context, Background

See https://github.com/hmdc/heroku-buildpack-r 

# How do we test this feature so that we know that it is done?
- CPU CORES / 2 instances of Shiny run by default in Heroku unless SHINY_NUM_PROCS environment variable is set.
- Tests

**Comment by doprdele** [comment]
I am currently working on this.

**Comment by doprdele** [comment]
Multi-processing support is now included. I committed to master, but, I will now write tests.

**Comment by doprdele** [comment]
Tests have been written and committed.

**Comment by doprdele** [comment]
For QA/Review:

* [x] Deploy sample Heroku Docker R app to Heroku. Follow instructions here. <https://github.com/hmdc/heroku-docker-r-example-app>. Does the app work when deployed? 
* [x] Run the app locally, following the above instructions, does it work?
* [x] Check whether the amount of R processes running are the cores available to the docker container divided by two. First, run the container locally, then run
  - ```docker exec -i -t ContainerId /bin/bash```
    - you can get the container id by running ```docker ps```
   - ```[ $(( $(grep -c processor /proc/cpuinfo 2>/dev/null) / 2 )) -eq $(pgrep R|wc -l) ] && echo "pass" || echo "fail"```
   - Pass means that there are the correct amount of R processes running.

**Comment by iqlinuxadmin** [comment]
All tests passed.
